version: '3.8'

services:
  pharmacy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OracleConnection=Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle-db)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)));User Id=pharmacy_user;Password=your_password;
      - Stripe__SecretKey=your_stripe_secret_key
      - Stripe__PublishableKey=your_stripe_publishable_key
    depends_on:
      - oracle-db
    volumes:
      - ./uploads:/app/wwwroot/uploads
      - ./logs:/app/logs
    networks:
      - pharmacy-network
    restart: unless-stopped

  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=your_password
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./database/init:/opt/oracle/scripts/startup
    networks:
      - pharmacy-network
    restart: unless-stopped

  redis-cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pharmacy-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./uploads:/var/www/uploads
    depends_on:
      - pharmacy-app
    networks:
      - pharmacy-network
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local
  redis_data:
    driver: local

networks:
  pharmacy-network:
    driver: bridge 